include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - no_logic_in_create_state
    - avoid_renaming_method_parameters
    - avoid_unnecessary_containers
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - constant_identifier_names
    - non_constant_identifier_names
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_spread_collections
    - unnecessary_new
    - require_trailing_commas
