name: community_internal
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  uuid: ^3.0.6
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  flutter_tags: ^0.4.9+1
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  image_picker: ^0.8.5+1
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4
  settings_ui: ^2.0.2
  readmore: ^2.1.0
  flutter_speed_dial: ^6.0.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Caladea
      fonts:
        - asset: assets/fonts/Caladea/Caladea-Regular.ttf
        - asset: assets/fonts/Caladea/Caladea-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
