// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_UserModel _$$_UserModelFromJson(Map<String, dynamic> json) => _$_UserModel(
      id: json['id'] as String?,
      userName: json['user_name'] as String?,
      userEmail: json['user_email'] as String?,
      mobileNumber: json['mobile_number'] as String?,
      gender: json['gender'] as String?,
      fatherName: json['father_name'] as String?,
      motherName: json['mother_name'] as String?,
      brotherName: json['brother_name'] as String?,
      sisterName: json['sister_name'] as String?,
      education: json['education'] as String?,
      highSchool: json['highschool'] as String?,
      interMediate: json['intermediate'] as String?,
      graduation: json['graduation'] as String?,
      postGraduation: json['post_graduation'] as String?,
      adharNumber: json['adhar_number'] as String?,
      passportNumber: json['passport_number'] as String?,
      password: json['password'] as String?,
      registrationDate: json['registration_date'] as String?,
      communityId: json['community_id'] as String?,
      societyId: json['society_id'] as String?,
      societyName: json['society_name'] as String?,
      countryId: json['country_id'] as String?,
      stateId: json['state_id'] as String?,
      cityId: json['city_id'] as String?,
      districtId: json['district_id'] as String?,
      pinCodeId: json['pincode_id'] as String?,
      gotraId: json['gotra_id'] as String?,
      address: json['address'] as String?,
      profile: json['profile'] as String?,
      status: json['status'] as String?,
      otp: json['otp'] as String?,
      userType: json['usertype'] as String?,
      referralCode: json['refferal_code'] as String?,
      joiningId: json['joining_id'] as String?,
    );

Map<String, dynamic> _$$_UserModelToJson(_$_UserModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'user_name': instance.userName,
      'user_email': instance.userEmail,
      'mobile_number': instance.mobileNumber,
      'gender': instance.gender,
      'father_name': instance.fatherName,
      'mother_name': instance.motherName,
      'brother_name': instance.brotherName,
      'sister_name': instance.sisterName,
      'education': instance.education,
      'highschool': instance.highSchool,
      'intermediate': instance.interMediate,
      'graduation': instance.graduation,
      'post_graduation': instance.postGraduation,
      'adhar_number': instance.adharNumber,
      'passport_number': instance.passportNumber,
      'password': instance.password,
      'registration_date': instance.registrationDate,
      'community_id': instance.communityId,
      'society_id': instance.societyId,
      'society_name': instance.societyName,
      'country_id': instance.countryId,
      'state_id': instance.stateId,
      'city_id': instance.cityId,
      'district_id': instance.districtId,
      'pincode_id': instance.pinCodeId,
      'gotra_id': instance.gotraId,
      'address': instance.address,
      'profile': instance.profile,
      'status': instance.status,
      'otp': instance.otp,
      'usertype': instance.userType,
      'refferal_code': instance.referralCode,
      'joining_id': instance.joiningId,
    };
